POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "esimerkkiotsikko2",
  "author": "esimerkkiauthor2",
  "url": "esimerkkiurl2",
  "likes": 1,
  "userId": "67b8a30e843fe585af64b5ba"
}
