POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpMiIsImlkIjoiNjdiOGJkMDg1NGU4YmE2Yjc2ODdlYzdiIiwiaWF0IjoxNzQwMTYwMjg3fQ.QPeHVj1nmNj9QxQgFxaTp0m9Y8akbPYy1WA4_OaXwSo

{
  "title": "esimerkkiotsikko2",
  "author": "esimerkkiauthor2",
  "url": "esimerkkiurl2",
  "likes": 1,
  "userId": "67b8a30e843fe585af64b5ba"
}
